export const LOAD_ICO_PARAMS = 'LOAD_ICO_PARAMS';

export const NEW_PHASE_ACTION = 'NEW_PHASE';

export const ICO_PHASES = {
  BEFORE_ICO: 'BEFORE_ICO',
  DURING_ICO: 'DURING_ICO',
  AFTER_ICO: 'AFTER_ICO',
  UNKNOWN: 'UNKNOWN',
};

export const LOAD_ICO_STATS = 'LOAD_ICO_STATS';

export const SET_USER_ADDRESS = 'SET_USER_ADDRESS';
export const SET_USER_LOADING = 'SET_USER_LOADING';
export const SET_USER_NEUMARKS = 'SET_USER_NEUMARKS';

export const LOAD_DEFAULT_ACCOUNT = 'LOAD_DEFAULT_ACCOUNT';
